In [1]:
import os
import inro.modeller as m

In [2]:
### IMPORT ALL MATRICES IN FOLDER ###

mm = m.Modeller()
NAMESPACE = "tmg.input_output.import_binary_matrix"
name2 = "inro.emme.data.matrix.matrix_transaction"
matrix311 = mm.tool(name2)
import_matrices = mm.tool(NAMESPACE)           
NAMESPACE = "inro.emme.data.matrix.change_matrix_properties"
change_matrix = m.Modeller().tool(NAMESPACE)
eb = m.Modeller().emmebank

matrix_folder = r"\\tore-infs01\PWExternal\451010\281829_GGH\GGHM Runs\2051\Preferred Network\Preferred_Network_SList_APTG_2051_GGH_MTP_V106A3_CS222_20210305\Trip Matrices"

for root, dirs, files in os.walk(matrix_folder):
    for matrix_file in files:
        if matrix_file.endswith(".mdf"):
            print matrix_file
            matrix_number = eb.available_matrix_identifier('FULL')
            import_matrices(4, matrix_number[2:] ,os.path.join(root, matrix_file),mm.scenario, matrix_file[:-4] )
            change_matrix(matrix = matrix_number,
                    matrix_name = matrix_file[:-4],
                  matrix_description = matrix_file[:-4])
            print "Imported matrix: " + matrix_file + " to: " + matrix_number
            
        elif matrix_file.endswith(".311"):
            print matrix_file
            matrix311(transaction_file = os.path.join(root, matrix_file),
                      throw_on_error = True,
                      scenario = mm.scenario)
            print "Imported 311 Matrix to specified matrix in file" + matrix_file
        
print "Finshed Importing Matrices"

trips_am_peak_auto1_nt.mdf
Imported matrix: trips_am_peak_auto1_nt.mdf to: mf34
trips_am_peak_auto1_toll.mdf
Imported matrix: trips_am_peak_auto1_toll.mdf to: mf35
trips_am_peak_auto2_nt_hov.mdf
Imported matrix: trips_am_peak_auto2_nt_hov.mdf to: mf36
trips_am_peak_auto2_nt_nh.mdf
Imported matrix: trips_am_peak_auto2_nt_nh.mdf to: mf37
trips_am_peak_auto2_toll_hov.mdf
Imported matrix: trips_am_peak_auto2_toll_hov.mdf to: mf38
trips_am_peak_auto2_toll_nh.mdf
Imported matrix: trips_am_peak_auto2_toll_nh.mdf to: mf39
trips_am_peak_auto3_nt_hov.mdf
Imported matrix: trips_am_peak_auto3_nt_hov.mdf to: mf40
trips_am_peak_auto3_nt_nh.mdf
Imported matrix: trips_am_peak_auto3_nt_nh.mdf to: mf41
trips_am_peak_auto3_toll_hov.mdf
Imported matrix: trips_am_peak_auto3_toll_hov.mdf to: mf42
trips_am_peak_auto3_toll_nh.mdf
Imported matrix: trips_am_peak_auto3_toll_nh.mdf to: mf43
trips_midday_auto1_nt.mdf
Imported matrix: trips_midday_auto1_nt.mdf to: mf44
trips_midday_auto1_toll.mdf
Imported matrix: trips_midday_auto1_toll.mdf to: mf45
trips_midday_auto2_nt_hov.mdf
Imported matrix: trips_midday_auto2_nt_hov.mdf to: mf46
trips_midday_auto2_nt_nh.mdf
Imported matrix: trips_midday_auto2_nt_nh.mdf to: mf47
trips_midday_auto2_toll_hov.mdf
Imported matrix: trips_midday_auto2_toll_hov.mdf to: mf48
trips_midday_auto2_toll_nh.mdf
Imported matrix: trips_midday_auto2_toll_nh.mdf to: mf49
trips_midday_auto3_nt_hov.mdf
Imported matrix: trips_midday_auto3_nt_hov.mdf to: mf50
trips_midday_auto3_nt_nh.mdf
Imported matrix: trips_midday_auto3_nt_nh.mdf to: mf51
trips_midday_auto3_toll_hov.mdf
Imported matrix: trips_midday_auto3_toll_hov.mdf to: mf52
trips_midday_auto3_toll_nh.mdf
Imported matrix: trips_midday_auto3_toll_nh.mdf to: mf53
trips_offpeak_active_bike.mdf
Imported matrix: trips_offpeak_active_bike.mdf to: mf54
trips_offpeak_active_walk.mdf
Imported matrix: trips_offpeak_active_walk.mdf to: mf55
trips_offpeak_transit_drive_to_and_from.mdf
Imported matrix: trips_offpeak_transit_drive_to_and_from.mdf to: mf56
trips_offpeak_transit_express_bus.mdf
Imported matrix: trips_offpeak_transit_express_bus.mdf to: mf57
trips_offpeak_transit_local_bus.mdf
Imported matrix: trips_offpeak_transit_local_bus.mdf to: mf58
trips_offpeak_transit_rapid_bus.mdf
Imported matrix: trips_offpeak_transit_rapid_bus.mdf to: mf59
trips_offpeak_transit_subway.mdf
Imported matrix: trips_offpeak_transit_subway.mdf to: mf60
trips_peak_active_bike.mdf
Imported matrix: trips_peak_active_bike.mdf to: mf61
trips_peak_active_walk.mdf
Imported matrix: trips_peak_active_walk.mdf to: mf62
trips_peak_transit_drive_to_and_from.mdf
Imported matrix: trips_peak_transit_drive_to_and_from.mdf to: mf63
trips_peak_transit_express_bus.mdf
Imported matrix: trips_peak_transit_express_bus.mdf to: mf64
trips_peak_transit_local_bus.mdf
Imported matrix: trips_peak_transit_local_bus.mdf to: mf65
trips_peak_transit_rapid_bus.mdf
Imported matrix: trips_peak_transit_rapid_bus.mdf to: mf66
trips_peak_transit_subway.mdf
Imported matrix: trips_peak_transit_subway.mdf to: mf67
trips_peak_transit_train.mdf
Imported matrix: trips_peak_transit_train.mdf to: mf68
trips_peak_transit_ztsa.mdf
Imported matrix: trips_peak_transit_ztsa.mdf to: mf69
trips_pm_peak_auto1_nt.mdf
Imported matrix: trips_pm_peak_auto1_nt.mdf to: mf70
trips_pm_peak_auto1_toll.mdf
Imported matrix: trips_pm_peak_auto1_toll.mdf to: mf71
trips_pm_peak_auto2_nt_hov.mdf
Imported matrix: trips_pm_peak_auto2_nt_hov.mdf to: mf72
trips_pm_peak_auto2_nt_nh.mdf
Imported matrix: trips_pm_peak_auto2_nt_nh.mdf to: mf73
trips_pm_peak_auto2_toll_hov.mdf
Imported matrix: trips_pm_peak_auto2_toll_hov.mdf to: mf74
trips_pm_peak_auto2_toll_nh.mdf
Imported matrix: trips_pm_peak_auto2_toll_nh.mdf to: mf75
trips_pm_peak_auto3_nt_hov.mdf
Imported matrix: trips_pm_peak_auto3_nt_hov.mdf to: mf76
trips_pm_peak_auto3_nt_nh.mdf
Imported matrix: trips_pm_peak_auto3_nt_nh.mdf to: mf77
trips_pm_peak_auto3_toll_hov.mdf
Imported matrix: trips_pm_peak_auto3_toll_hov.mdf to: mf78
trips_pm_peak_auto3_toll_nh.mdf
Imported matrix: trips_pm_peak_auto3_toll_nh.mdf to: mf79
Finshed Importing Matrices

In [7]:
import pandas as pd

mats = []
for i in range(34, 79):
    mats.append("mf{}".format(i))

def mat_to_pddf(id, scen):
    mat = eb.matrix(id).get_data(scen)
    zones_tupl = mat.indices
    indices = pd.Index(zones_tupl[0])
    indices.name = 'p'
    cols = pd.Index(zones_tupl[1])
    cols.name = 'q'
    matrix = mat.to_numpy()
    return pd.DataFrame(matrix, index=indices, columns=cols)

In [13]:
for mat in mats:
    print('converted {}'.format(mat))
    mat = mat_to_pddf(mat, 404)

converted mf34
converted mf35
converted mf36
converted mf37
converted mf38
converted mf39
converted mf40
converted mf41
converted mf42
converted mf43
converted mf44
converted mf45
converted mf46
converted mf47
converted mf48
converted mf49
converted mf50
converted mf51
converted mf52
converted mf53
converted mf54
converted mf55
converted mf56
converted mf57
converted mf58
converted mf59
converted mf60
converted mf61
converted mf62
converted mf63
converted mf64
converted mf65
converted mf66
converted mf67
converted mf68
converted mf69
converted mf70
converted mf71
converted mf72
converted mf73
converted mf74
converted mf75
converted mf76
converted mf77
converted mf78

In [14]:
modes = {"sov":['trips_peak_hbw_auto1_nt', 'trips_peak_hbw_auto1_toll'],
        "hov2": ['trips_peak_hbw_auto2_nt_hov', 'trips_peak_hbw_auto2_nt_nh',
       'trips_peak_hbw_auto2_toll_hov', 'trips_peak_hbw_auto2_toll_nh'],
        "hov3": ['trips_peak_hbw_auto3_nt_hov', 'trips_peak_hbw_auto3_nt_nh',
       'trips_peak_hbw_auto3_toll_hov', 'trips_peak_hbw_auto3_toll_nh'],
        "Express Bus": ['trips_peak_hbw_transit_express_bus_walk','od_trips_peak_hbw_transit_express_bus_drive'],
        "Rapid Bus": ['trips_peak_hbw_transit_rapid_bus_walk','trips_peak_hbw_transit_rapid_bus_drive'],
        "Local Bus": ['trips_peak_hbw_transit_local_bus_walk','trips_peak_hbw_transit_local_bus_drive'],
        "Train":['od_trips_peak_hbw_transit_train_walk_access',
       'od_trips_peak_hbw_transit_train_transit_access',
       'od_trips_peak_hbw_transit_train_park_access',
       'od_trips_peak_hbw_transit_train_drop_off'],
        "Subway": ['od_trips_peak_hbw_transit_subway_walk_access',
       'od_trips_peak_hbw_transit_subway_transit_access',
       'od_trips_peak_hbw_transit_subway_park_access',
       'od_trips_peak_hbw_transit_subway_drop_off'],
        "walk": ['trips_peak_hbw_active_walk'],
        "bike": ['trips_peak_hbw_active_bike']}

# peak period - 7 hrs
sov_demand_pk = "TRIPS SOV peak"
hov2_demand_pk = "TRIPS HOV2 peak"
hov3_demand_pk = "TRIPS HOV3 peak"
bike_demand_pk = "TRIPS BIKE peak"
walk_demand_pk = "TRIPS WALK peak"
transit_demand_pk = "TRIPS TOTAL TRANSIT peak"

sov_demand_offpk = "TRIPS SOV offpeak"
hov2_demand_offpk = "TRIPS HOV2 offpeak"
hov3_demand_offpk = "TRIPS HOV3 offpeak"
bike_demand_offpk = "TRIPS BIKE offpeak"
walk_demand_offpk = "TRIPS WALK offpeak"
transit_demand_offpk = "TRIPS TOTAL TRANSIT offpeak"

NameError: name 'mf78' is not defined

In [7]:
import pandas as pd
path = r"C:\Users\BCRANE\Documents"
fle = "mf1.csv"
matrix = os.path.join(path,fle)
df = pd.read_csv(matrix)
df.head()

,p/q/[val],1001,1002,1003,1004,1005,1006,1007,1008,1009,...,9950,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,1001,666.787720,446.423248,764.643494,243.304672,516.204041,568.442200,87.493156,150.090469,199.293259,...,0,0,0,0,0,0,0,0,0,0
1,1002,523.235413,1073.461670,1325.037842,936.624756,1056.706421,382.693634,207.350189,386.782959,209.470581,...,0,0,0,0,0,0,0,0,0,0
2,1003,171.045425,357.888794,2122.519287,774.762451,304.594696,146.308197,525.599060,1138.444336,122.315224,...,0,0,0,0,0,0,0,0,0,0
3,1004,127.062157,402.091949,1214.834961,518.864502,287.642242,115.679420,254.910385,319.476654,103.786079,...,0,0,0,0,0,0,0,0,0,0
4,1005,67.719803,172.481384,238.389984,91.750389,135.935974,136.959412,23.430912,73.805145,72.208084,...,0,0,0,0,0,0,0,0,0,0

In [8]:
rural = pd.read_csv(os.path.join(path,"GGHMZonesRural.csv"))

    taz  @ruralFlag
0  1001           0
1  1002           0
2  1003           0
3  1004           0
4  1005           0

In [38]:
#df.head()
#rural["@ruralFlag"]
#df.tail()
#df[df["p/q/[val]"] == 1001].loc[:,"1001"] #= 0
#df[df["p/q/[val]"] == 1001]["1001"]
#df.head()
df["p/q/[val]"].to_csv(os.path.join(path,"realZones.csv"))

In [14]:
rural["taz"]

0     1001
1     1002
2     1003
3     1004
4     1005
5     1006
6     1007
7     1008
8     1009
9     1010
10    1011
11    1012
12    1013
13    1014
14    1015
...
3087    9317
3088    9318
3089    9319
3090    9320
3091    9321
3092    9322
3093    9323
3094    9324
3095    9325
3096    9326
3097    9327
3098    9328
3099    9329
3100    9330
3101    9331
Name: taz, Length: 3102, dtype: int64

In [ ]:
for row in rural.iterrows():