In [16]:
import pandas as pd

pth = r'C:\Users\pechen\Desktop\VTP\SkM\distance_mat.txt'
distance = pd.read_csv(pth, sep = '\s+')
dist_mat = distance.pivot(index='root', columns='leaf', values='cost').fillna(0)
dist_mat.to_csv(r'C:\Users\pechen\Desktop\VTP\SkM\dist_mat.csv')

In [38]:
import numpy as np
pth = r'C:\Users\pechen\Desktop\VTP\SkM\dist_mat.csv'
dist_matrix = pd.read_csv(pth, index_col = 0)
dist_matrix

,1,2,3,4,5,6,7,8,9,10,...,9779,9780,9781,9819,9822,9823,9824,9825,9827,9828
root,,,,,,,,,,,,,,,,,,,,,
1,0.000000,1.126571,1.475368,2.306067,2.978132,3.133824,3.852770,3.047698,5.459677,4.451992,...,28.17227,29.716880,17.39781,16.816540,12.64343,19.768370,21.069750,21.885810,24.483010,25.727690
2,1.126571,0.000000,1.037045,1.220762,2.166589,1.656292,2.376054,1.570166,3.992958,2.985273,...,27.56876,29.113360,16.79429,17.936020,13.76291,19.732640,21.034030,21.850080,24.447290,25.691970
3,1.475368,1.037045,0.000000,0.714333,1.520659,1.680762,2.399708,1.594636,4.006615,2.998930,...,26.92283,28.467430,16.14836,17.803840,13.63073,19.086710,20.388100,21.204150,23.801360,25.046040
4,2.306067,1.220762,0.714333,0.000000,0.809799,0.797559,1.658850,1.638477,3.265757,2.258072,...,26.29432,27.838920,15.44900,18.649820,14.47672,18.841410,20.142800,20.958850,23.556060,24.800740
5,2.978132,2.166589,1.520659,0.809799,0.000000,0.692868,1.554159,1.875479,2.681661,1.673976,...,25.77898,27.323580,14.93366,19.321890,15.14878,18.326070,19.627460,20.443510,23.040710,24.285400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9822,12.643430,13.762910,13.630730,14.476720,15.148780,15.416940,16.162090,15.357020,17.769000,16.761310,...,28.96215,30.506760,22.47729,4.398267,0.00000,19.271690,20.424730,21.240790,23.297930,23.616700
9823,19.768370,19.732640,19.086710,18.841410,18.326070,19.079080,19.940370,20.261690,19.149010,18.396860,...,10.19639,11.740990,16.17603,15.401450,19.37037,0.000000,1.828083,2.644139,5.241342,6.486025
9824,21.069750,21.034030,20.388100,20.142800,19.627460,20.380460,21.241750,21.563070,20.450390,19.698250,...,9.07027,10.531930,17.47741,16.554490,20.52341,1.828083,0.000000,1.492722,4.089925,5.334608
9825,21.885810,21.850080,21.204150,20.958850,20.443510,21.196520,22.057810,22.379130,21.266450,20.514300,...,10.35222,9.919702,18.29347,17.370540,21.33946,2.644139,1.492722,0.000000,2.826069,4.070752
9827,24.483010,24.447290,23.801360,23.556060,23.040710,23.793720,24.655010,24.976330,23.863650,23.111510,...,11.63089,10.760430,20.89067,19.067730,23.29793,5.241342,4.089925,2.826069,0.000000,1.411883

In [41]:
intradist = pd.read_csv(r'C:\Users\pechen\Desktop\VTP\SkM\zonedist.csv', index_col=0)

In [42]:
intradist

      Intrazonal Distance
TAZ
1              241.202713
2              362.063994
3              156.510884
4              167.675367
5              235.954874
...                   ...
9822             0.000000
9823             0.000000
9824             0.000000
9825             0.000000
9827             0.000000

[2532 rows x 1 columns]

In [50]:
s = pd.Series(intradist['Intrazonal Distance'], index=intradist.index)
s = s/1000

np.fill_diagonal(dist_matrix.values, s)
dist_matrix.to_csv(r'C:\Users\pechen\Desktop\VTP\SkM\dist_mat.csv')